name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "VIRTUAL_ENV=${{ github.workspace }}/venv" >> $GITHUB_ENV
        echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        source venv/bin/activate        
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        ruff check src --fix

    - name: Format code
      run: |
        ruff format src

    - name: Run type checks
      run: |
        mypy src

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Build distribution
      run: |
        source venv/bin/activate
        python -m build

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: |
          dist/*.tar.gz
          dist/*.whl
    - name: Install the package in editable mode
      run: |
          pip install -e .

    - name: Run script
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        python -m src.main