name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        ruff check src

    - name: Format code
      run: |
        ruff fmt src

    - name: Run type checks
      run: |
        mypy src

    - name: Run tests
      run: |
        pytest

    - name: Build distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: |
          dist/*.tar.gz
          dist/*.whl
